application: face2-143523
version: 1
runtime: python27
api_version: 1
threadsafe: false

libraries:
- name: PIL
  version: "latest"
- name: jinja2
  version: "latest"

handlers:
- url: /face3\.jpg
  static_files: face3.jpg
  upload: face3\.jpg
  application_readable: true
  
- url: /face2\.jpg
  static_files: face2.jpg
  upload: face2\.jpg
  application_readable: true

- url: /(.+\.(css|js))$
  static_files: \1
  upload: .+\.(css|js)$
  application_readable: true
  
- url: /css
  static_dir: css
 
- url: /js
  static_dir: js
  
- url: /img
  static_dir: img

- url: /.*
  script: faces.app

