application: face2-143523
version: 1
runtime: python27
api_version: 1
threadsafe: false

libraries:
- name: PIL
  version: "latest"
- name: jinja2
  version: "latest"

handlers:
- url: /faces
  static_files: face3.jpg
  upload: face3\.jpg

- url: /(.+\.(css|js))$
  static_files: \1
  upload: .+\.(css|js)$
  application_readable: true

- url: /.*
  script: faces.app

